### ISSUE TITLE
Better error messaging

### ISSUE THREAD

**Issue by jerelmiller** [PRX/speechmatics#12]
Currently when speechmatics rejects transcripts, a 40x error is returned. Accordingly to the [documentation](https://app.speechmatics.com/api-details#getJobs) it looks like there are also error reasons returned in the response. It would be nice to get information on why something was rejected instead of just the `Whoops, error back from Speechmatics: 400` style error.

The current exception raised makes it very difficult to determine why speechmatics is rejecting transcripts or alignment requests.

**Comment by kookster** [comment]
Hi Jerel, thanks for the issue. I'm not using this gem much these days, so I'm unlikely to make such an improvement myself, but I would welcome a PR if you felt like it was worth making.

**Comment by jerelmiller** [comment]
Good to know. Thanks for getting back to me! I'll try and take some time soon to get something in here as I'm sure it will be useful for others.

**Comment by Blaze34** [comment]
any updates?
