### ISSUE TITLE
Doesn't work with Faraday 0.7.6

### ISSUE THREAD

**Issue by kookster** [PRX/speechmatics#5]
It is tested and works with 0.8.8 and 0.9.0

  1) Error:
Speechmatics::Client#test_0001_lists jobs:
NameError: wrong constant name mashify
    /Users/andrew/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/faraday-0.7.6/lib/faraday.rb:32:in `const_get'
    /Users/andrew/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/faraday-0.7.6/lib/faraday.rb:32:in`lookup_module'
    /Users/andrew/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/faraday-0.7.6/lib/faraday/builder.rb:151:in `use_symbol'
    /Users/andrew/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/faraday-0.7.6/lib/faraday/builder.rb:107:in`response'
    /Users/andrew/dev/projects/speechmatics/lib/speechmatics/connection.rb:43:in `block in connection'
    /Users/andrew/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/faraday-0.7.6/lib/faraday/connection.rb:46:in`block in initialize'
    /Users/andrew/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/faraday-0.7.6/lib/faraday/builder.rb:12:in `block in create'
    /Users/andrew/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/faraday-0.7.6/lib/faraday/builder.rb:65:in`build'
    /Users/andrew/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/faraday-0.7.6/lib/faraday/builder.rb:54:in `initialize'
    /Users/andrew/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/faraday-0.7.6/lib/faraday/builder.rb:12:in`new'
    /Users/andrew/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/faraday-0.7.6/lib/faraday/builder.rb:12:in `create'
    /Users/andrew/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/faraday-0.7.6/lib/faraday/connection.rb:46:in`initialize'
    /Users/andrew/dev/projects/speechmatics/lib/speechmatics/connection.rb:39:in `new'
    /Users/andrew/dev/projects/speechmatics/lib/speechmatics/connection.rb:39:in`connection'
    /Users/andrew/dev/projects/speechmatics/lib/speechmatics/api.rb:39:in `request'
    /Users/andrew/dev/projects/speechmatics/lib/speechmatics/api.rb:68:in`list'
    /Users/andrew/dev/projects/speechmatics/test/user/jobs_test.rb:91:in `block (2 levels) in <top (required)>'

**Comment by pkarman** [comment]
addressed in a0c272fb32e6405af63546a24b4c9134bb77d957
