### ISSUE TITLE
Add support for mp4 videos

### ISSUE THREAD

**Issue by marvs** [PRX/speechmatics#6]
Based on Speechmatics FAQs, mp4 videos are supported:
https://speechmatics.com/support

I tested this and they were able to transcribe mp4 videos. Attaching mp4 videos when creating jobs will fail since the content type does not match the allowed types in the "attach_audio" method:

https://github.com/PRX/speechmatics/blob/a0c272fb32e6405af63546a24b4c9134bb77d957/lib/speechmatics/user/jobs.rb#L32

Pull request incoming :)

**Comment by kookster** [comment]
from a file size perspective, you may want to actually convert to just the audio before sending to speechmatics.  sending along the video content just means longer to upload and hitting limits on file size sooner.

That said, it is supported by SM, so the gem should as well. I'll take a look at the PR.
